### ISSUE TITLE
Get requirements from the Pharmacy team

### ISSUE THREAD

**Issue by razekmh** [SAFEHR-data/ramses-package#16]
TLDR: get expectation final target output of the project

Background: The expected outcome of the project will be used by the pharmacy team. Understanding what are the expectations form the pharmacy team will help us guide the development of OMOP integration into RAMSES

- [ ] Set up a meeting with Pharmacy team
- [ ] Meet the team and Get basic requirements
- [ ] Plan development of the output 
- [ ] Reflect on the integration development

**Comment by zsenousy** [comment]
### **Meeting 30 August 2024 - OMOP discussion**
@skeating, @razekmh, and @zsenousy met with Steve and Tim to discuss initial issues and walkthrough OMOP. We had a discussion regarding our understanding to RAMSES package of the focus of exploring drug prescriptions and administrations and how we link this to OMOP data extract that Tim will provide to us by Wednesday 4 September.

Conclusions from the meeting:

- Initial steps for us will be to understand RAMSES primary data and identify any derived data so that we can map the required data from OMOP to RAMSES validation and visualisation functions.
- Build High-level bridge between RAMSES and OMOP with highlighting what RAMSES functions operated correctly to OMOP and listing out functions with possible issues for future
- Meet with medical professionals to get concrete use cases which will identify how to test RAMSES after integration with OMOP.
- Use Slab https://slab.com/ for writing notes as Steve recommended.

**Comment by docsteveharris** [comment]
@z.senousy thanks for this ☝️ ; moved the 1st 2 bullet points to the overview, and I think we've also nailed down the third in the description there.

**Comment by razekmh** [comment]
We have one concrete use case which is "How much of a drug X is used in time period Y at a location Z?" We hope to have a meeting with the pharmacy team to collect more concrete use cases
